### ISSUE TITLE
MXNetError: Check failed: fi->Read(data): Invalid NDArray file format

### ISSUE THREAD

**Issue by chentao2016** [KAIST-vilab/AEFT#2]
After creating conda environment with the provided yaml file, I tried to train the model and encountered this error. I have checked the version of  mxnet. Could you provide suggestions to solve it？

>>> import mxnet
>>> mxnet.__version__
'1.8.0'

Start experiment rp!
Train dataset is loaded from voc12/train_aug.txt
Validation dataset is loaded from voc12/train.txt
Traceback (most recent call last):
  File "train.py", line 113, in <module>
    model = getattr(importlib.import_module('models.model_'+args.model), 'model_WSSS')(args, logger)
  File "/home/ct/weak2023/AEFT/models/model_aeft_gpp.py", line 117, in __init__
    self.net_main.load_state_dict(resnet38d.convert_mxnet_to_torch('./pretrained/resnet_38d.params'), strict=False)
  File "/home/ct/weak2023/AEFT/networks/resnet38d.py", line 132, in convert_mxnet_to_torch
    save_dict = mxnet.nd.load(filename)
  File "/home/ct/anaconda3/envs/wsss_ksj/lib/python3.8/site-packages/mxnet/ndarray/utils.py", line 171, in load
    check_call(_LIB.MXNDArrayLoad(c_str(fname),
  File "/home/ct/anaconda3/envs/wsss_ksj/lib/python3.8/site-packages/mxnet/base.py", line 246, in check_call
    raise get_last_ffi_error()
mxnet.base.MXNetError: Traceback (most recent call last):
  File "../src/ndarray/ndarray.cc", line 1861
MXNetError: Check failed: fi->Read(data): Invalid NDArray file format

**Comment by yoon307** [comment]
I am not sure about this error, since we encounter such an error the first time.
In my opinion, the followings should be compatible [gpu driver, cuda version, mxnet version]. 
If possible, create your own conda env (instead of using ours).
(FYI, the provided conda env is checked on RTX 3090. )
